name: location_mocker
description: A comprehensive Flutter plugin for GPS location mocking, route manipulation, and GPX file handling
version: 0.0.1
homepage: https://github.com/amrahmed242/location_mocker

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  xml: ^6.2.0
  http: ^0.13.4
  retry: ^3.1.2
  permission_handler: ^11.0.1
  downloadsfolder: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  path: ^1.8.3
  path_provider: ^2.0.15

flutter:
  plugin:
    platforms:
      android:
        package: com.example.location_mocker
        pluginClass: LocationMockerPlugin
